Label change
rpa-tomorrow/rpa-models pull request #10
Opened 2020-10-29 09:42 UTC by viktorfrom

2020-10-29 10:05 UTC, markhakansson requested changes

2020-10-29 10:05 UTC, markhakansson commented on simple/datasets/email/training_data.py
> +# Labels: [ROOT, NOUN, TO, START, BODY]
Don't change other datasets

2020-10-29 10:05 UTC, markhakansson commented on simple/datasets/reminder/training_data.py
> +# Labels: [ROOT, NOUN, TO, START, BODY]
Same here don't change other datasets

2020-10-29 10:05 UTC, markhakansson commented on deep/seq2seq.py
> +                       "remind <TO> me <START> 8am tomorrow <BODY> Take out the trash.",
Don't change the model Alex is maintaining

2020-10-29 10:07 UTC, markhakansson requested changes

2020-10-29 10:07 UTC, markhakansson commented on deep/seq2seq.py
> +        print("Training WHENed")
WTF

2020-10-29 10:32 UTC, Blinningjr commented on simple/datasets/reminder/training_data.py
> +        "warn me WHEN the time is 20.15",
CAPS

2020-10-29 13:51 UTC, Blinningjr approved these changes

2020-10-30 08:39 UTC, markhakansson approved these changes

2020-10-30 08:51 UTC, merged